# Generated by Django 2.2.3 on 2019-07-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='myfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
