# Generated by Django 2.2.3 on 2019-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190727_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='myfile',
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
